---

- hosts: localhost
  gather_facts: false
  vars:
    f5_username: '{{ f5_username }}'
    f5_password: '{{ f5_password }}'
    token: '{{ nb_password }}'

  tasks:
  - debug:
      msg: |-
        {% for k in _my_vars %}
        {{ k }}: {{ lookup('vars', k) }}
        {% endfor %}
      
