---

- hosts: all
  gather_facts: false
  tasks:
    - name: Reading Out Environment Variables
      debug:
        msg: "{{ lookup('env','F5_USERNAME','F5_PASSWORD','NB_PASSWORD') }}"
    - name: Reading Out Extra Variables
      debug:
        msg: "{{ extra-vars('h-inventory','lbgrp','port','partition','pool','addrm','disabled') }}"
  
